CREATE TABLE "contact"
(
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_subject" VARCHAR(255)                            NOT NULL,
    "type"         VARCHAR(255)                            NOT NULL,
    "value"        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_contact PRIMARY KEY ("id")
);

CREATE TABLE "identity"
(
    "uid"        VARCHAR(255) NOT NULL,
    "name"       VARCHAR(255),
    "department" VARCHAR(255),
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    CONSTRAINT pk_identity PRIMARY KEY ("uid")
);

CREATE TABLE "occupation_card"
(
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "status"     TINYINT DEFAULT 0                       NOT NULL,
    "matter"     VARCHAR(255),
    "returns_at" TIMESTAMP,
    "leaves_at"  TIMESTAMP,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    CONSTRAINT pk_occupationcard PRIMARY KEY ("id")
);

CREATE TABLE "user"
(
    "subject"      VARCHAR(255) NOT NULL,
    "identity_uid" VARCHAR(255),
    "card_id"      BIGINT,
    "created_at"   TIMESTAMP,
    "updated_at"   TIMESTAMP,
    CONSTRAINT pk_user PRIMARY KEY ("subject")
);

ALTER TABLE "contact"
    ADD CONSTRAINT FK_CONTACT_ON_USER_SUBJECT FOREIGN KEY ("user_subject") REFERENCES "user" ("subject");

ALTER TABLE "user"
    ADD CONSTRAINT FK_USER_ON_CARD FOREIGN KEY ("card_id") REFERENCES "occupation_card" ("id");

ALTER TABLE "user"
    ADD CONSTRAINT FK_USER_ON_IDENTITY_UID FOREIGN KEY ("identity_uid") REFERENCES "identity" ("uid");
